version: 2
jobs:
  build:
    docker:
      # Note: Raspbian stretch actually has Python 3.5.3, but CircleCI's images
      # don't offer exactly that combination. We go with the closest we can,
      # even this is likely on the wrong patch version.
      - image: python:3.5-stretch

    steps:
      - checkout
      - run: python3 -m venv venv
      - run: venv/bin/pip install -r script/linting/requirements.txt
      - run: venv/bin/pip install -r script/typing/requirements.txt
      - run:
          command: script/linting/lint
          environment:
            FLAKE8: venv/bin/flake8
      - run:
          command: script/typing/check
          environment:
            MYPY: venv/bin/mypy
